ABCSalesApp/Controllers/CityController.cs
using ABCSalesApp.Extension.AppCustom;
using ABCSalesApp.Models;
using ABCSalesApp.Models.ViewModels;
using ABCSalesApp.Repositories;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace ABCSalesApp.Controllers
{
    public class CityController : Controller
    {
        private CityRepository _repository {  get; set; }
        private SelectItemReposity _selectHelper { get; set; }

        public CityController()
        {
            _repository = new CityRepository();
            _selectHelper = new SelectItemReposity();
        }

        // GET: City
        public ActionResult Index(int? currentPage)
        {
            return View(_repository.GetGridDatas(!currentPage.HasValue ? 1 : currentPage.Value));
        }

        // GET: City/Details/5
        public ActionResult Details(string id)
        {
            if(string.IsNullOrEmpty(id))
                return RedirectToAction("Index");

            return View(_repository.GetDetailById(id));
        }

        // GET: City/Create
        public ActionResult Create()
        {
            var data = new CityModifyViewModels();
            data.Countries = _selectHelper.GetCoutries();

            return View(data);
        }


        // POST: City/Create
        [HttpPost]
        public ActionResult Create(CityModifyViewModels data)
        {
            data.Countries = _selectHelper.GetCoutries(data.CountryId);
            data.States = _selectHelper.GetStates(data.CountryId,data.StateId);

            try
            {
                if (!ModelState.IsValid)
                {
                    return View(data);
                }

                // TODO: Add insert logic here
                _repository.SaveNewRecord(data);

                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                ex.LogError();

                return View(data);
            }
        }

        // GET: City/Edit/5
        public ActionResult Edit(string id)
        {
            if (string.IsNullOrEmpty(id))
                return RedirectToAction("Index");

            var data = _repository.GetDetailToEditById(id);

            if (data == null)
            {
                return RedirectToAction("Index");
            }

            data.Countries = _selectHelper.GetCoutries(data.CountryId);
            data.States = _selectHelper.GetStates(data.CountryId, data.StateId);

            return View(data);
        }

        // POST: City/Edit/5
        [HttpPost]
        public ActionResult Edit(CityModifyViewModels data)
        {
            data.Countries = _selectHelper.GetCoutries(data.CountryId);
            data.States = _selectHelper.GetStates(data.CountryId, data.StateId);

            try
            {
                if (!ModelState.IsValid)
                {
                    return View(data);
                }
                // TODO: Add update logic here
                _repository.UpdateRecord(data);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ex.LogError();

                return View(data);
            }
        }

        // GET: City/Delete/5
        public ActionResult Delete(string id)
        {
            if (string.IsNullOrEmpty(id))
                return RedirectToAction("Index");

            var data = _repository.GetDetailById(id);

            if (data == null)
            {
                return RedirectToAction("Index");
            }

            return View(data);
        }

        // POST: City/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeletePost(string id)
        {
            if (string.IsNullOrEmpty(id))
                return RedirectToAction("Index");

            try
            {
                // TODO: Add delete logic here
                _repository.DeleteRecord(id);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ex.LogError();
                return View(new CityDetailViewModels());
            }
        }
    }
}

ABCSalesApp/Controllers/CountryController.cs
using ABCSalesApp.Extension.AppCustom;
using ABCSalesApp.Models.ViewModels;
using ABCSalesApp.Repositories;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace ABCSalesApp.Controllers
{
    public class CountryController : Controller
    {
        private CountryRepository _repository { get; set; }

        public CountryController()
        {
            _repository = new CountryRepository();
        }

        // GET: Country
        public ActionResult Index(int? currentPage)
        {
            return View(_repository.GetGridDatas(!currentPage.HasValue ? 1 : currentPage.Value));
        }

        // GET: Country/Details/5
        public ActionResult Details(string id)
        {
            if (string.IsNullOrEmpty(id))
                return RedirectToAction("Index");

            return View(_repository.GetDetailById(id));
        }

        // GET: Country/Create
        public ActionResult Create()
        {
            return View(new CountryModifyViewModels());
        }

        // POST: Country/Create
        [HttpPost]
        public ActionResult Create(CountryModifyViewModels data)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(data);
                }
                // TODO: Add insert logic here
                _repository.SaveNewRecord(data);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ex.LogError();
                return View(data);
            }
        }

        // GET: Country/Edit/5
        public ActionResult Edit(string id)
        {
            if (string.IsNullOrEmpty(id))
                return RedirectToAction("Index");

            var data = _repository.GetDetailToEditById(id);

            if(data == null)
            {
                return RedirectToAction("Index");
            }

            return View(data);
        }

        // POST: Country/Edit/5
        [HttpPost]
        public ActionResult Edit(CountryModifyViewModels data)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(data);
                }
                // TODO: Add update logic here
                _repository.UpdateRecord(data);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ex.LogError();
                return View(data);
            }
        }

        // GET: Country/Delete/5
        public ActionResult Delete(string id)
        {
            if (string.IsNullOrEmpty(id))
                return RedirectToAction("Index");

            var data = _repository.GetDetailById(id);

            if (data == null)
            {
                return RedirectToAction("Index");
            }

            return View(data);
        }

        // POST: Country/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeletePost(string id)
        {
            if (string.IsNullOrEmpty(id))
                return RedirectToAction("Index");

            try
            {
                // TODO: Add delete logic here
                _repository.DeleteRecord(id);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ex.LogError();
                return View(new CountryDetailViewModels());
            }
        }
    }
}

ABCSalesApp/Controllers/SalesController.cs
using ABCSalesApp.Extension.AppCustom;
using ABCSalesApp.Models.ViewModels;
using ABCSalesApp.Repositories;
using System;
using System.Reflection;
using System.Web.Mvc;

namespace ABCSalesApp.Controllers
{
    public class SalesController : Controller
    {
        private SalesRepository _repository { get;set; }
        private SelectItemReposity _selectHelper { get; set; }
        public SalesController()
        {
            _repository = new SalesRepository();
            _selectHelper = new SelectItemReposity();
        }
        // GET: Sales
        public ActionResult Index()
        {
            var data = TempData["parameter"];

            if(data != null)
            {
               
                var result = _repository.GetGridDatas((SalesSearchParameter)data);
                result.SalesSearchParameter.Countries = _selectHelper.GetCoutries(result.SalesSearchParameter.CountryId);
                result.SalesSearchParameter.States = _selectHelper.GetStates(result.SalesSearchParameter.CountryId, result.SalesSearchParameter.StateId);
                result.SalesSearchParameter.Cities = _selectHelper.GetCities(result.SalesSearchParameter.CountryId, result.SalesSearchParameter.StateId, result.SalesSearchParameter.CityId);
                return View(result);
            }

            var datas = _repository.GetGridDatas(new SalesSearchParameter
            {
                CurrentPage = 1,
                Countries = _selectHelper.GetCoutries()
            });

            return View(datas);
        }

        [HttpPost]
        public ActionResult SearchSales(SalesSearchParameter data)
        {
            if(data == null)
                return RedirectToAction("Index");

            TempData["parameter"] = data;

            return RedirectToAction("Index");
        }
        // GET: Sales/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Sales/Create
        public ActionResult Create()
        {
            var model = new SalesModifyViewModels();
            model.Products = _selectHelper.GetProducts();
            model.Countries = _selectHelper.GetCoutries();

            return View(model);
        }

        // POST: Sales/Create
        [HttpPost]
        public ActionResult Create(SalesModifyViewModels data)
        {
            data.Products = _selectHelper.GetProducts(data.ProductId);
            data.Countries = _selectHelper.GetCoutries(data.CountryId);
            data.States = _selectHelper.GetStates(data.CountryId, data.StateId);
            data.Cities = _selectHelper.GetCities(data.CountryId, data.StateId, data.CityId);
            
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(data);
                }

                // TODO: Add insert logic here
                _repository.SaveNewRecord(data);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ex.LogError();
                return View(data);
            }
        }

        // GET: Sales/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Sales/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Sales/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Sales/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ABCSalesApp/Controllers/StateController.cs
using ABCSalesApp.Extension.AppCustom;
using ABCSalesApp.Models.ViewModels;
using ABCSalesApp.Repositories;
using System;
using System.Data;
using System.Web.Mvc;

namespace ABCSalesApp.Controllers
{
    public class StateController : Controller
    {
        private StateRepository _repository { get; set; }
        private SelectItemReposity _selectHelper { get; set; }

        public StateController()
        {
            _repository = new StateRepository();
            _selectHelper = new SelectItemReposity();
        }

        // GET: State
        public ActionResult Index(int? currentPage)
        {
             var datas = _repository.GetGridDatas(!currentPage.HasValue ? 1 : currentPage.Value);
             return View(datas);
        }

        // GET: State/Details/5
        public ActionResult Details(string id)
        {
            if (string.IsNullOrEmpty(id))
                return RedirectToAction("Index");

            return View(_repository.GetDetailById(id));
        }

        // GET: State/Create
        public ActionResult Create()
        {
            var data = new StateModifyViewModels();
            data.Countries = _selectHelper.GetCoutries();

            return View(data);
        }

        // POST: State/Create
        [HttpPost]
        public ActionResult Create(StateModifyViewModels data)
        {
            data.Countries = _selectHelper.GetCoutries(data.CountryId);

            try
            {
                if (!ModelState.IsValid)
                {
                    return View(data);
                }
                // TODO: Add insert logic here
                _repository.SaveNewRecord(data);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ex.LogError();
                return View(data);
            }
        }

        // GET: State/Edit/5
        public ActionResult Edit(string id)
        {
            if (string.IsNullOrEmpty(id))
                return RedirectToAction("Index");

            var data = _repository.GetDetailToEditById(id);

            if (data == null)
            {
                return RedirectToAction("Index");
            }

            data.Countries = _selectHelper.GetCoutries(data.CountryId);

            return View(data);
        }

        // POST: State/Edit/5
        [HttpPost]
        public ActionResult Edit(StateModifyViewModels data)
        {
            data.Countries = _selectHelper.GetCoutries(data.CountryId);

            try
            {
                if (!ModelState.IsValid)
                {
                    return View(data);
                }

                // TODO: Add update logic here
                _repository.UpdateRecord(data);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ex.LogError();
                return View(data);
            }
        }

        // GET: State/Delete/5
        public ActionResult Delete(string id)
        {
            if (string.IsNullOrEmpty(id))
                return RedirectToAction("Index");

            var data = _repository.GetDetailById(id);

            if (data == null)
            {
                return RedirectToAction("Index");
            }

            return View(data);
        }

        // POST: State/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeletePost(string id)
        {
            if (string.IsNullOrEmpty(id))
                return RedirectToAction("Index");

            try
            {
                // TODO: Add delete logic here
                _repository.DeleteRecord(id);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ex.LogError();
                return View();
            }
        }
    }
}

ABCSalesApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - ABC Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css" />

</head>
<body id="body-pd">
    <div class="l-navbar" id="nav-bar">
        <nav class="nav">
            <div>
                <a href="@Url.Action("Index", "Sales")" class="nav_logo"> <i class='bx bx-layer nav_logo-icon'></i> <span class="nav_logo-name">Sales Information</span> </a>
                <div class="nav_list">
                    <a href="@Url.Action("Index", "Sales")" class="nav_link active">
                        <i class='bx bx-grid-alt nav_icon'></i>
                        <span class="nav_name">Dashboard</span>
                    </a>
                    <a href="@Url.Action("Create", "Sales")" class="nav_link"> <i class='bx bx-user nav_icon'></i> <span class="nav_name">Sales</span> </a>
                    <a href="@Url.Action("Index", "Product")" class="nav_link"> <i class='bx bx-box nav_icon'></i> <span class="nav_name">Product</span> </a>
                    <a href="@Url.Action("Index", "Country")" class="nav_link"> <i class='bx bx-globe nav_icon'></i> <span class="nav_name">Country</span> </a>
                    <a href="@Url.Action("Index", "State")" class="nav_link"> <i class='bx bx-arch nav_icon'></i> <span class="nav_name">State</span> </a>
                    <a href="@Url.Action("Index", "City")" class="nav_link"> <i class='bx bx-building-house nav_icon'></i> <span class="nav_name">City</span> </a>
                </div>
            </div> <a href="#" class="nav_link"> <i class='bx bx-log-out nav_icon'></i> <span class="nav_name">SignOut</span> </a>
        </nav>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - ABC Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ABCSalesApp/Views/Shared/_PaginationFilterNavBar.cshtml
@model ABCSalesApp.Models.ViewModels.PaginationBaseViewModel

<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-end">
        <li class="page-item @(Model.DisablPrev ? "disabled" : "")" )>
            <a class="page-link" id="filter-prev-page-id" aria-label="Previous" style="cursor: @(Model.DisablPrev ? "not-allowed" : "pointer")">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
            </a>
        </li>

        @foreach (var index in Model.PageIndexes)
        {
            <li class="page-item @(index == Model.CurrentPages?"active":"") @(index > Model.TotalPages?"disabled":"")"><a class="page-link filter-current-page" href="#">@index</a></li>

        }

        <li class="page-item @(Model.DisablNext ? "disabled" : "")" )>
            <a class="page-link" id="filter-next-page-id" aria-label="Next" style="cursor: @(Model.DisablNext ? "not-allowed" : "pointer")">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
            </a>
        </li>
    </ul>
</nav>

ABCSalesApp/Views/Shared/_PaginationNavBar.cshtml
@model ABCSalesApp.Models.ViewModels.PaginationBaseViewModel

<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-end">
        <li class="page-item @(Model.DisablPrev ? "disabled" : "")" )>
            <a class="page-link" id="prev-page-id" aria-label="Previous" style="cursor: @(Model.DisablPrev ? "not-allowed" : "pointer")">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
            </a>
        </li>

        @foreach (var index in Model.PageIndexes)
        {
            <li class="page-item @(index == Model.CurrentPages?"active":"") @(index > Model.TotalPages?"disabled":"")"><a class="page-link current-page" href="#">@index</a></li>

        }

        <li class="page-item @(Model.DisablNext ? "disabled" : "")" )>
            <a class="page-link" id="next-page-id" aria-label="Next" style="cursor: @(Model.DisablNext ? "not-allowed" : "pointer")">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
            </a>
        </li>
    </ul>
</nav>